name: Go AKS CI/CD

on:
  workflow_call:
    inputs:
      aks-cluster:
        required: true
        type: string

      aks-resource-group:
        required: true
        type: string

      acr-name:
        required: true
        type: string

      helm-release:
        required: true
        type: string

      helm-chart-path:
        required: true
        type: string

      namespace:
        required: true
        type: string

      go-version:
        required: true
        type: string



    secrets:
      AZURE_CLIENT_ID:
        required: true

      AZURE_TENANT_ID:
        required: true

      AZURE_SUBSCRIPTION_ID:
        required: true


jobs:
  build:
        runs-on: ubuntu-latest

        permissions:
          id-token: write
          contents: read

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Go
            uses: actions/setup-go@v5
            with:
              go-version: ${{ inputs.go-version }}  

